[package]
name = "mbrot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.19.0"
egui = "0.19.0"
itertools = "0.10.5"
num-traits = "0.2.15"
rayon = "1.5.3"
